yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'


urlpatterns = [
    path(
        'author/',
        views.AboutAuthorView.as_view(),
        name='author'
    ),
    path(
        'tech/',
        views.AboutTechView.as_view(),
        name='tech'
    ),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'groups'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_update, name='post_update'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
    PasswordResetView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordResetDoneView
)
from django.urls import path

from . import views


app_name = 'users'


urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'),
        name='logout'),
    path(
        'signup/',
        views.SingUp.as_view(),
        name='signup'),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'),
        name='login'),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='registration/password_reset_form.html'),
        name='password_reset_form'),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='registration/password_change_form.html'),
        name='password_change_form'),
    path(
        'password_change/done',
        PasswordChangeDoneView.as_view(
            template_name='registration/password_change_done.html'),
        name='password_change_done_form'),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='registration/password_reset_form.html'),
        name='password_reset_form'),
    path(
        'password_reset/done',
        PasswordResetDoneView.as_view(
            template_name='registration/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(
        'reset/done',
        PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler403csrf = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }}  Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/forms_errors.html
{% if form.errors %}
{% for field in form %} 
  {% for error in field.errors %}            
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
{% endfor %}
{% endif %}

yatube/templates/includes/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
<link rel ="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

yatube/templates/includes/header.html
 {% load static %}
 <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
          <ul class="nav  nav-pills">
            {% with request.resolver_match.view_name as view_name %}
            <li class="nav-item">              
              <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
                 href="{% url 'about:author' %}">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
                 href="{% url 'about:tech' %}">
                Технологии
              </a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" 
              href="{% url 'posts:post_create' %}">
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link {% if view_name  == 'users:password_change_form' %}active{% endif %}" 
                 href="{% url 'users:password_change_form' %}">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="{% url 'posts:profile' user.username %}">
                <img src="{% static 'img/profile.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                {{ user.username }}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">
                <span style="color:red">Вы</span>йти
              </a>
            </li>
            {% else %}
            <li class="nav-item"> 
              <a class="nav-link link-light" href="{% url 'users:login' %}">
                <img src="{% static 'img/unregistered.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                <span style="color:red">Во</span>йти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="{% url 'users:signup' %}">Регистрация</a>
            </li>
            {% endif %}
            {% endwith %}
          </ul>      
        </div>
      </nav> 
    </header>