yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'


urlpatterns = [
    path(
        'author/',
        views.AboutAuthorView.as_view(),
        name='author'
    ),
    path(
        'tech/',
        views.AboutTechView.as_view(),
        name='tech'
    ),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'groups'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_update, name='post_update'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler403csrf = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Группа'
    )
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст нового поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='user',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        related_name="posts_group",
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        help_text='Загрузите картинку',
        null=True,
        blank=True
    )
    comment = models.ForeignKey(
        'Comment',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Комментарий'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        blank=False,
        null=False,
        verbose_name='Комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        blank=False,
        null=False,
        verbose_name='Комментарий'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Текст нового комментария'
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор подписки'

    )
    create_date = models.DateTimeField(
        'Дата подписки',
        auto_now_add=True,
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return f'{self.follower} подписан на {self.following}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from .utils import get_page


def index(request):
    posts_list = Post.objects.select_related('author')
    page_obj = get_page(posts_list, request)
    context = {
        'page_obj': page_obj,
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_group_lists = group.posts_group.all()
    page_obj = get_page(post_group_lists, request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=user).exists()
    page_obj = get_page(user.user.all(), request)
    context = {
        'page_obj': page_obj,
        'author': user,
        'user': request.user,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_update(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return render(request, 'posts/update_post_not_author.html')
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'post': post
    }
    return render(request, 'posts/update_post.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect(
            'posts:profile', request.user.username
        )
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """
    Страница подписок пользователя
    """
    posts = Post.objects.select_related('author', 'group').filter(
        author__following__user=request.user
    )
    context = {
        'page_obj': get_page(posts, request),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    following = get_object_or_404(User, username=username)
    follower = request.user
    if follower != following and (
        not follower.user.filter(author=following).exists()
    ):
        Follow.objects.get_or_create(user=follower, author=following)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    follow_true = Follow.objects.filter(
        author__username=username,
        user=request.user)
    if follow_true.exists():
        follow_true.delete()
        return redirect('posts:profile', username)
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Редактировать пост {% endblock %}
{% block content %}
{% include 'posts/includes/open_divs.html' %}
<div class="card-header">       
  Новый пост             
</div>
<div class="card-body">    

  <form method="post" enctype="multipart/form-data"
  {% if action_url %}
  action="{% url action_url %}">
  {% endif %}
  >
    {% csrf_token %}           
    <div class="form-group row my-3 p-3">
      {% for field in form %} 
        {% include 'posts/includes/fields_form.html' %}
      {% endfor %}
      </div>
    <div class="d-flex justify-content-end">
      <button type="submit" class="btn btn-primary">
        Сохранить
      </button>
    </div>
  </form>
</div>
{% include 'posts/includes/close_divs.html' %}
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %} Подписчики {% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' with follow=True%}
<div class="container py-5">
  <article>
      {% for post in page_obj %}
          {% include 'posts/includes/body_follow_posts.html' %}
      {% empty %}
        <h2> У вас отсутствуют подписки </h2>
      {% endfor %}
  </article>
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} {{ group }} {% endblock %}     
{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>  
      {% if group.description != "Null" %}
        {{ group.description }}
      {% endif %}
  </p>       
  {% for post in page_obj %}
   {% include 'posts/includes/body_groups.html' %}
   {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' with index=True %}
<div class="container py-5">
  <h1>Записи сообщества: Лев Толстой – зеркало русской революции</h1>
  <p>Группа тайных поклонников графа</p>
  {% cache 20 index_page %}
  <article>
    {% for post in page_obj %} 
      {% include 'posts/includes/body_index.html' %}
    {% endfor %} 
  </article>
  {% include 'posts/includes/paginator.html' %}
  {% endcache %}
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост {{ post.text|truncatechars:30 }} {% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    {% include 'posts/includes/body_post_detail_info.html' %}
    {% include 'posts/includes/body_post_detail.html' %}
  </div>     
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Профайл пользователя {{ author.username }} {% endblock %}
{% block content %}
<div class="container py-5">
  <div class="mb-5">        
    <h1>Все посты пользователя {{ author.username }} </h1>
    <h3>Всего постов: {{ user.user.count }} </h3>
    <h4>Всего комментариев {{ author.comments.count }} </h3>
    <h5>Всего подписчиков {{ author.following.count }} </h4>
    {% if request.user != author and request.user.is_authenticated %}
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
   {% endif %}
  </div>
    {% for post in page_obj %} 
      {% include 'posts/includes/body_profile.html' %}     
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/update_post.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Редактировать пост {% endblock %}
{% block content %}
{% include 'posts/includes/open_divs.html' %}
<div class="card-header">       
  Редактировать пост             
</div>
  <div class="card-body"> 

    <form method="post" enctype="multipart/form-data" 
    {% if action_url %}
    action="{% url action_url %}">
    {% endif %}
    >
      {% csrf_token %}

      <div class="form-group row my-3 p-3">
      {% for field in form %} 
        {% include 'posts/includes/fields_form.html' %}
      {% endfor %}
      </div>
      <div class="d-flex justify-content-end">
        <button type="submit" class="btn btn-primary">
          Добавить
        </button>
      </div>
    </form>
  </div>
{% include 'posts/includes/close_divs.html' %}
{% endblock %}

yatube/templates/posts/update_post_not_author.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Редактировать пост {% endblock %}
{% block content %}
{% include 'posts/includes/open_divs.html' %}
<div class="card-header">       
  Редактирование поста запрещено             
</div>
  <div class="card-body"> 
    <p>
      Нет доступа к редактированию поста, вы не являетесь его автором
    </p>
  </div>
{% include 'posts/includes/close_divs.html' %}
{% endblock %}