yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'


urlpatterns = [
    path(
        'author/',
        views.AboutAuthorView.as_view(),
        name='author'
    ),
    path(
        'tech/',
        views.AboutTechView.as_view(),
        name='tech'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
    PasswordResetView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordResetDoneView
)
from django.urls import path

from . import views


app_name = 'users'


urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'),
        name='logout'),
    path(
        'signup/',
        views.SingUp.as_view(),
        name='signup'),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'),
        name='login'),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='registration/password_reset_form.html'),
        name='password_reset_form'),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='registration/password_change_form.html'),
        name='password_change_form'),
    path(
        'password_change/done',
        PasswordChangeDoneView.as_view(
            template_name='registration/password_change_done.html'),
        name='password_change_done_form'),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='registration/password_reset_form.html'),
        name='password_reset_form'),
    path(
        'password_reset/done',
        PasswordResetDoneView.as_view(
            template_name='registration/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(
        'reset/done',
        PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler403csrf = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm

from posts.models import User


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SingUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %} Вы вышли из системы {% endblock %}
{% block content %}
{% include 'users/includes/open_divs.html' %}
  <div class="card-header">
    Выход
  </div>
  <div class="card-body">
    <p>
      Вы вышли из своей учётной записи. Ждём вас снова!
    </p>
  </div>
{% include 'users/includes/close_divs.html' %}
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% load user_filters %}
{% block title %} Войти {% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
{% include 'users/includes/hello_auth_user.html' %}
{% else %}
{% include 'users/includes/open_divs.html' %}
<div class="card-header">
  Войти на сайт
</div>
<div class="card-body">
  {% include 'includes/forms_errors.html' %}
  <form method="post" action="{% url 'users:login' %}">
  {% csrf_token %}
  
  {% for field in form %}
    <div class="form-group row my-3"
      {% if field.field.required %} 
      aria-required="true"
      {% else %}
      aria-required="false"
      {% endif %}
    >
      {% include 'users/includes/fields_form.html'%}
    </div>
  {% endfor %}
  <div class="col-md-6 offset-md-4">
    <button type="submit" class="btn btn-primary">
      Войти
    </button>
    <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
      Забыли пароль?
    </a>
  </div>
  </form>
</div>
{% endif %}
{% include 'users/includes/close_divs.html' %}
{% endblock %} 

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %} Зарегистрироваться {% endblock %}
{% block content %}
{% include 'users/includes/open_divs.html' %}
<div class="card-header">Зарегистрироваться</div>
  <div class="card-body">
    {% include 'includes/forms_errors.html' %}
    <form method="post" action="{% url 'users:signup' %}">
      {% csrf_token %}

    {% for field in form %}
    <div class="form-group row my-3">
      {% include 'users/includes/fields_form.html'%}
    </div>
    {% endfor %}
    <div class="col-md-6 offset-md-4">
      <button type="submit" class="btn btn-primary">
        Зарегистрироваться
      </button>
    </div>
    </form>
  </div>
{% include 'users/includes/close_divs.html' %}
{% endblock %} 